<?
return [
       'text-01' => "Main",
       'text-02' => "Training",
       'text-03' => "HEALINGBOWL® KNOWLEDGE BASE",
       'text-04' => "Certificate training",
       'text-05' => "Healingbowl® Open Knowledge Base",
       'text-06' => "Everything you need to know about the singing bowl",
       'text-07' => "Using our techniques and high-quality low-frequency Healingbowl® singing bowls, you can achieve a variety of health benefits. These include relief from pinched nerves, improved blood properties, reduced muscle tension, pain relief, enhanced metabolic processes, faster recovery from injuries, prevention of many diseases, quicker treatment, strong detox effects, and rejuvenated facial skin.
       <br><br>
       Not all singing bowls are suitable for this purpose, and we can help you understand the differences between them. Just read on.",
       'text-08' => "                    <strong>You may already know that the sound of forged singing bowls</strong> is soothing, helping you relax and find inner peace. You might have also heard that spaces where singing bowls are played become more harmonious. 
       <br><br>
       However, you may not be aware of the. <strong>bowls' vibration features</strong>. Sound is vibration, and the impact of singing bowls can be greatly enhanced by placing a professional-quality forged singing bowl on the body, generating vibrations. 
                           </p>
                           <p>
                                Over the years, we have taught hundreds of people around the world to use this feature. Healingbowl® Singing bowls are used by massage therapists, psychotherapists, spa specialists, reflexologists, neurologists, and even intensive care doctors in their professional activities. However, our methods can be easily mastered, even without extensive education.

                               <br><br>",
       'text-09' => "Contents of the Healingbowl® Knowledge Base",
       'text-10' => "Cast and Forged Singing Bowl Differences.",
       'text-11' => "Sizes: Small and Large Singing Bowls.",
       'text-12' => "Frequency of Singing Bowls",
       'text-13' => "Vibration of Singing Bowls.",
       'text-14' => "Quality: Manufacturing Standards",
             'text-15' => "Singing Bowls Healingbowl®",
             'text-17' => "Aesthetics: Artistic Design.",
     'text-18' => "Accessories: Singing Bowl Tools and Application Techniques.",
       'text-19' => "Singing Bowl Sets: Harmony Unleashed.",
       'text-20' => "Chakra Note Correspondence.",
       'text-21' => "Singing Bowl for Massage.",
       'text-22' => "Singing Bowl for Meditation.",
       'text-23' => "Singing Bowl Therapy.",
       'text-24' => "Cast and Forged Singing Bowl Differences",
       'text-25' => "                <p>
       Each cast singing bowl sounds one tone (maximum two). In the sound of a forged singing bowl, you hear several “voices” at once. It’s the main tone (the lowest), and some higher ones (overtones). All of them, at the same time, pulsate and move. From this point of view, forged singing bowls are more attractive. The structure of the crystal lattice of the metal changes in the process of manual forging, getting the characteristic tension. That is why the forged singing bowl sound is more complex and attractive.
       </p>
       <p>The advantage of cast singing bowls is their low cost. They can also be beautiful. Cast bowls easily begin to “sing” if you drive the stick in a circular motion along the edge of the wall. This is surprising and mesmerizing. All this makes them a perfect inexpensive gift. For a beginner, they bring a lot of joy, especially if they are high-quality bowls, for example, the well-known brand Healingbowl®, which also produces molded bowls for the mass market.
Over time, you may get interested in something more. It is  forged bowls and singing bowl sets.
</p>",
       'text-26' => "Sizes: Small and Large Singing Bowls",
       'text-27' => "<p>
       All singing bowls produce sounds in the range of the human voice. For different singing bowls with the same wall thickness, you notice that the larger the diameter, the lower the tone of the sound. Small bowls produce high-pitched “childish” voices that attract attention, allow you to escape from worries, and give a charge of positive emotions. At the same time, their sound is harmonious and calming. This makes them valuable. With multiple bowls, you can engage in 'musical' creativity, without needing specialized knowledge or skills. Your listeners can also appreciate the experience. The bowls are great for tea ceremonies, sound therapy, psychotherapy, yoga, and meditation where maintaining a clear mind is essential.
       </p>
       <p>Remember the rule: the lower the sound's tone, the more soothing it is. A bowl with a larger diameter produces a lower frequency. The frequency shifts from 'childish' to 'female' and eventually to calm 'male' voices. At some point, a large singing bowl induces a state of light trance, comparable to deep meditation or light superficial sleep. In this state, a person rests and recuperates more effectively than during normal sleep. It's challenging to pinpoint which frequency is considered calming, as it varies depending on individual perception and initial state. It's quite simple to determine the right bowl for you – even if you're inexperienced. Just listen and observe how your mood changes. Trust your subjective experience.</p>
       <p>In addition to diameter, a bowl's wall thickness also influences its pitch. If we compare two bowls with the same diameter but different wall thicknesses, the bowl with a thicker wall produces a higher frequency sound. Moreover, a thick-walled bowl typically has a longer and more 'robust' sound. </p>",
       'text-28' => "Frequency of Singing Bowls",
       'text-29' => "<p>In discussing this crucial aspect, there's a lot to take into account. It's important to understand that the bowl resonates at numerous frequencies at once, generating an active and dynamic acoustic field. Thus, the bowl is unsuitable as a musical instrument, and discussing the precise frequencies is not essential. The lowest frequency within the sound range produced by the bowl is regarded as the fundamental, which has the most profound impact on a person's psyche and well-being. This frequency is referred to as the 'bowl frequency.' Furthermore, we hear several overtones (higher pitches) that can vary from being very close to the fundamental to much higher. These factors contribute to the multidimensional quality of the singing bowl's sound. </p>
       <p>Dfferent tools can produce diverse sounds, particularly for larger bowls (20cm or bigger). For instance, the mallet (also known as the gong stick or striker) is used to obtain the deepest and lowest sound that the bowl can produce. The softness and heaviness of the mallet have a clear impact on how distinct the lower tones will sound. Naturally, each bowl has its limits or range of sound. For instance, a bowl with a diameter of 28cm and a fundamental tone of E at 80Hz can produce the overtone of C at 550Hz and has a broad range filled with other overtones. Similarly, a bowl with the note C at 134Hz can have the overtone of G at 770Hz. Striking the bowl's edge with a hard stick creates higher sounds. The lighter and harder the stick, the higher overtones it produces. In order to produce the full frequency range, tapping with a hard stick and then striking with a soft mallet is recommended.</p>
       <p>The richness and healthfulness of the acoustic impact depend on how uniformly the overtone range is filled and how harmoniously the overtones blend together.</p>",
       'text-30' => "Vibration of Singing Bowls",
       'text-31' => "<p>Naturally, all singing bowls vibrate, as sound is a vibration. Hearing a sound indicates that the bowl is vibrating. Lower frequency vibrations, however, have a more significant impact on fluids and the human body all in all. To structure water, opt for a bowl with a diameter of at least 20 cm and a medium or thin wall. Larger diameters (lower frequencies) yield more favorable effects on water structure, which is a subject worth its own article.</p>
       <p>For massage purposes, choose a bowl with a primary frequency no higher than 180 Hz. Frequencies between 160 and 180 Hz provide shallow, localized, yet noticeable effects on the body. Lower frequencies result in deeper, more extensive, and beneficial impacts. A frequency of 150 Hz or lower makes the bowl versatile for both acoustic and vibrational ('massage') uses. With a frequency of 120 Hz or lower, a singing bowl can serve as a full-fledged physiotherapy tool, depending on its manufacturing quality. Consider the professional line of Healingbowl® singing bowls, specifically designed to guarantee favorable effects and comfortable sound and vibration control. These bowls are user-friendly, even for novices.
</p>",
       'text-32' => "Quality: Manufacturing Standards",
       'text-33' => "<p>Cast singing bowls have a simple principle: their sound mainly relies on the alloy composition, with copper as the predominant element. Typically, a harder alloy like bronze produces a brighter sound than brass. </p>
       <p>Forged singing bowls exhibit greater complexity, with the forging process being a key factor. Greater effort yields better results. While some bowls can be swiftly formed, others require multiple forging cycles (heating, forging, cooling) and extra methods to enhance quality. Processing time influences sound quality more than alloy composition complexity.

Avoid relying solely on what traders claim about alloy composition. Firstly, the composition is typically secret. Secondly, the forging process is vital. Additionally, factors such as even wall thickness, edge processing quality, and bowl shape contribute to the overall outcome, influencing sound quality and vibrations. High-quality souvenir products are often scarce due to mass production for souvenirs in Nepal and India. Nonetheless, some exceptional ones exist. The Healingbowl® logo on a bowl serves as the only quality guarantee, as these bowls are custom-made and undergo rigorous quality control checks for all parameters.</p>
       <p>The more overtones present, the better the experience. A rich, saturated sound range increases immersion value. Harmonious interactions between overtones improve quality. Additionally, longer-lasting sounds are preferable. For a bowl to be suitable for massage, it should easily vibrate when a solid stick glides along its edge. The motion should be smooth, without jerks, slips, or extra sounds, while maintaining the lowest frequency vibrations (the bowl's fundamental tone). If you hear rattling or the bowl 'singing' (producing high-frequency sounds), it may be due to a lack of skill. </p>

       <p>Our video tutorials can help with this. However, some bowls might be designed solely for auditory pleasure and not for massage. Consulting with Healingbowl® consultants when choosing a singing bowl (or a set) ensures your choice aligns with your needs and abilities. Video tests can also help when selecting a bowl from an online store. The tutorials showcase the bowl's capabilities, highlighting high overtones, the fundamental tone, and its ability to maintain low-frequency vibrations when a solid stick glides along the edge. The tests also demonstrate the bowl's ability to produce high-pitched 'singing' sounds using various gliding techniques. We meticulously select bowls for our stores, ensuring they meet high-quality standards and do not disappoint.
</p>",
       'text-34' => "Singing Bowls Healingbowl®",
       'text-35' => "<p>Healingbowl® is a registered trademark, protected against counterfeits in multiple countries. Our company has put in significant effort to produce singing bowls using the most advanced technologies, ensuring top-notch quality. The secrets of master craftsmen are never used for mass production of common singing bowl types. If you see the Healingbowl® logo on a singing bowl, you can trust its high quality, advanced technology, and strict control. The logo is a brilliant indicator of premium craftsmanship. You simply need to choose the design, purpose, and size. Healingbowl® offers several lines of professional and collectible singing bowls, each with unique designs and purposes.</p>",
       'text-36' => "Aesthetics: Artistic Design",
       'text-37' => "<p>Images on singing bowls often have roots in Tibetan Buddhist culture, reflecting local traditions. It's essential to note that these bowls are not religious artifacts, as our research shows that Tibetan monasteries don't use them in their practices. In fact, Tibetan monks and lamas often learned about singing bowls from us. Therefore, avoid considering a singing bowl as a religious item. The imagery mainly represents Tibetan culture, and if unfamiliar with the images, they can have a similar effect to abstract graphics, providing a general impact. Simple drawings may seem charming and mysterious, while more refined artwork can evoke a sophisticated perception.
 </p>
 <p>Singing bowls often depict ornamental elements symbolizing the lotus, sun's movement, and features of Kalachakra. Common symbols include the eternity knot of Dharma teachings, 'Buddha's eyes' (a Lemurian symbol), and the 'eight auspicious symbols' representing well-wishes like health and success. It's believed that a singing bowl transmits these symbols' meanings and energies into the surrounding space, but more accurately, it conveys your state, mood, and intention.
 </p>
        <p>Alongside ornamental elements, human figures such as bodhisattvas, White or Green Tara, Manjushri, Buddha, Avalokiteshvara, and Chenrezig from Tibetan culture may be present. Less commonly, Ganesha or Shiva may appear, as well as the 'Flower of Life.' Healingbowl® singing bowls can feature highly artistic images, especially on collector's items. However, professional Healingbowl® singing bowls, meant for restorative medicine and spa professionals, only display the logo without additional imagery. Labeled as 'professional,' these bowls possess all the essential qualities, are convenient to work with, and their lack of images makes them suitable for a wider audience.
 </p>",
       'text-38' => "Accessories: Singing Bowl Tools and Application Techniques",
       'text-39' => "<p>We've already mentioned two main accessories for singing bowls: the stick and the mallet (also called a gong stick or 'striker'). The stick should be made from heavy, hard wood, wrapped in thick suede to avoid sharp sounds when touched, and encourage low-frequency vibrations during rotation. Mastering the complex rotational technique helps develop fine motor skills and sensitivity. If the bowl can produce both fundamental (through rotation) and high frequencies (singing),If a bowl is capable of vibrating at the fundamental frequency (using a rotational technique) and at a high frequency (singing), all you need to do is master the nuances of the technique, all you need to do is master the nuances of the technique. To achieve low-frequency 'massage' vibrations, hold the stick correctly (see our video lessons or attend in-person training), slightly touch the bowl's edge, and swiftly slide the stick along the edge, positioning it closer to a vertical angle. To use the stick on a singing bowl, hold it by the suede part near the bowl contact area, and imagine drawing a circle around the bowl like using a thick pencil. Keep your wrist relaxed, make swift movements, and apply minimal pressure. The vibration should appear quickly. Before it turns into a rattle (you'll learn to sense this moment), slow down your movement by half and slightly increase pressure. Continue rotating to maintain the vibration. Aim for about 70% of the possible intensity. Increasing the stick's angle will dampen the vibration. Choose a larger stick with good inertia for best results.</p>
       <p>To produce 'singing,' adjust your technique. Begin with a 45-degree angle of inclination and perform slow, fluid motions. Create friction by applying pressure with the suede-covered stick along the edge. Gently strike the edge for a high sound, but keep it soft. A lighter stick with firm, thin suede may be more suitable for this method.</p>
       <p>To engage the lower sound range, use a mallet. Flick its weighted end at the edge, making contact with the ridge and allowing it to continue in the original direction. Keep your hand relaxed. A heavier, softer weight yields deeper sounds, while a smaller-diameter, rigid weight creates a richer sound. Consult experts for selection advice. Having various sticks and mallets ensures diverse sounds and enriches the experience. Notably, lightweight mallets with long handles are ideal for acoustic massage sessions with bowls placed around the body. </p>",
       'text-40' => "Singing Bowl Sets: Harmony Unleashed",
       'text-41' => "<p>Resonance occurs when sounds interact, including overtones from a single bowl, creating a dynamic acoustic hologram. Harmonious patterns have positive effects, and we choose such bowls for our stores. The sound from multiple singing bowls generates potent resonance in an acoustic space, so selecting ones with the right harmonics is essential. Combining bowls can lead to either harmony or dissonance. Musical mathematics helps us pair bowls based on their main frequencies to achieve harmony. Knowing your bowl's frequency allows us to find a compatible match, making accurate frequency determination vital.
</p>
       <p>Adding a new beautiful bowl to your home collection might yield surprising results, as not all bowls produce harmonious sounds together. Bowls can either complement or conflict with each other. By applying musical mathematics and knowing your bowl's frequency, we can find a harmonious match. Accurate frequency determination is vital. You may be surprised that many manufacturers and traders in Nepal may not do this correctly. Until recently, even just five years ago, almost none could. While they might now be able to create harmonious sets, we haven't observed it. Our Healingbowl® experts' intellect and experience allow for achieving the highest possible harmony in our sets. </p>",
       'text-42' => "Chakra Note Correspondence",
       'text-43' => "<p>With enough sensitivity, one can observe that certain notes can trigger reactions in specific body areas, producing subtle sensations that vary in nature. These sensations may be interpreted as energy flow effects such as intensification, focusing, or dispersal. Identifying the relationship between chakra notes and these effects is crucial, requiring a solid foundation in the system used. First and foremost, it's essential to determine the system. We base our practice on the quint (fifth), as Eastern healing systems that used music for healing also relied on the quint. Pythagoras, famous for 'music of the spheres' and soul healing, also utilized the quint. Our research, using advanced scientific equipment, showed a 30% advantage of the quint over the octave for singing bowl sounds.</p>

       <p>Vedic systems discussing chakra note correspondence reportedly indicate the following sequence: 1: F (F#), 2: C (C#), 3: G (G#), 4: D (D#), 5: A (A#), 6: E, 7: B (quint). During the early stages of our research (2013), when it was still possible to find a skilled master-tradition bearer in Nepal, they also adhered to the quint sequence. Later, traders adapted to the updated Western system, offering the octave sequence to avoid debates with esoteric tourists. If you're accustomed to the octave and it works for you, that's excellent. You'll be able to choose singing bowls at our store based on the C, D, E, F, G, A, B (including sharps) sequence.</p>
       <p>For a general understanding, you may find the following information helpful. In ancient healing traditions, the F note corresponds to the first chakra, which is associated with the Earth element, symbolizing acceptance, security, and comfort, as well as the skeletal system and muscles. The C note corresponds to the second chakra, which is connected to water, fluidity, fertility, and the reproductive system. The G note represents the third chakra, associated with fire, willpower, confidence, strength, and the stomach and digestive system. The D note corresponds to the fourth chakra (air) and is related to feelings and the heart. The A note represents the fifth chakra, connected to ether, life events, karma, and the thyroid gland. The E note is linked to the sixth chakra, associated with intuition and the pineal gland. The B note refers to the seventh chakra, which connects to a higher plane but is not directly related to the body. It's also worth noting that the same note can sound very different in various octaves. For example, D in the second (large) octave sounds extremely low and deep (74 Hz), while D in the third (small) octave aligns with a normal female voice (147 Hz), and D in the fourth (first) octave is a fairly high-pitched tone (293 Hz), similar to a teenager's voice. </p>
       <p>In which situations is this relevant? When choosing your first singing bowl, particularly if targeting a specific chakra, gaining experience is valuable. However, it's important to prioritize a sound that brings you comfort. If a bowl aligns with your concept but lacks comfort, it might not be a wise investment. Make sure to verify this aspect.</p>
       <p>It's important to note that if you plan on performing massages, the tonality is not a significant factor. In contact techniques, lower frequencies are more effective. Consequently, the fewer hertz, the better – as this relates to physics. Keep in mind that when performing massages, tonality is less significant. For contact techniques, lower frequencies tend to be more effective. As a result, fewer hertz are preferable. It is physics.</p>",
       'text-44' => "Singing Bowl for Massage",
       'text-45' => "<p>A singing bowl for massage is an ideally designed tool, when it’s specifically created for use in contact techniques. The bowl should have smooth, even walls that are rigid yet elastic enough to generate an intense and consistent vibration. The vibration frequency deemed effective ranges from 170 Hz down. Naturally, the diameter of the bowl should measure at least 22-23 cm. At 170 Hz, the effect is fairly localized. However, as the frequency decreases, the impact becomes broader and deeper. This connection is attributed to the physical wave properties of the vibrations. For a massage bowl, the lowest frequency we typically encounter is about 75 Hz.
 </p>
 <p>There's no need to strictly adhere to a 'lower is better' mentality. At different times and for different people and body regions, bowls with higher frequencies, such as 120 - 145 Hz, may be also required. Nevertheless, it's essential to have a primary low-frequency bowl.</p>
 <p>A common misbelief is that different bowls with varying frequencies are needed for specific organs. This idea stems from imaginative authors rather than a firm grasp of physiological processes. The previously explained frequency patterns are adequate. When selecting a 'massage' bowl, there's no need to link it to chakras, since contact massage mainly targets the physical body. Even when placing a bowl on the head, we don't consider the 7th chakra, but rather expect effects like lymphatic drainage, circulatory system restoration, and tension relief, all of which are related to the physical body.</p>
 <p>In addition to frequency, important factors involve edge processing quality, wall shape, and elements that ensure easy vibratory effects when using the unique solid stick technique. This method consists of sliding the suede-covered stick along the wall's edge. An even vibration without fluctuations or overtones at the singing bowl's primary frequency is ideal. We refer to this parameter as 'manageability.' Controlling the vibration should be effortless, comfortable, and not require significant skill, creating the impression that the 'bowl vibrates on its own.'</p>
 <p>Healingbowl®'s professional lines, like Silver Pearl, Golden Pearl, and Surya Pearl, exemplify all the mentioned qualities. These bowls are specially designed for professional use and cannot be found in ordinary souvenir shops. While it's possible to discover an affordable, thin-walled bowl with acceptable vibration—since the technological complexity isn't too high—its simplified production process won't yield high-quality sound. Besides their 'massage' capabilities, Healingbowl® bowls consistently provide a comfortable, unique sound, which is a crucial element.</p>",
 'text-46' => "Singing Bowl for Meditation",
 'text-47' => "<p>People often ask which singing bowl is best for meditation. The answer is quite simple. Take a high-quality bowl without the massage-specific requirements, and you'll have a perfect meditation bowl. A comfortable, long-lasting harmonic sound will aid in immersive meditation. Avoid the notion that you need to target a specific chakra, as many of these ideas are random and erroneous. Comfort remains key in meditation. It's important to remember that meditation demands concentration. Holding the singing bowl in your hands, its calming sound is vital for focus. Given what we discussed about frequencies and quality, clear sound will come naturally. Rather than relying on an external expert claiming to 'know what you need,' trust your instincts. You'll likely recognize the warmth, comfort, relaxation, and even sympathy or attraction that the bowl's sound may invoke. This phenomenon is known as 'positive resonance.'
</p>
 <p>Besides the sound, tactile and visual sensations also play a role. While these influences might not be as obvious, they are still quite significant. For instance, compare a mass-market item to a work of art - they are perceived differently. 'Cute and simple' represents one mood, 'simplified symbolism' another, 'understated elegance' a third, and 'refined artistry' yet another. Each of these distinct states will resonate within your life as you become attuned to them. A collectible singing bowl is a work of art in both its appearance and vibrations. Focusing on a remarkable piece, crafted with a master's skill and inspiration, delivers a one-of-a-kind meditation experience.</p>",
       'text-48' => "Singing Bowl Therapy",
       'text-49' => "<p>For effective singing bowl therapy, it's essential to precisely assess the patient's condition, establish a diagnosis, and prescribe the appropriate treatment. It's clear that you must be a medical professional with the appropriate education and experience for this endeavor. If you're not a doctor, you cannot treat people with singing bowls or anything else. However, if you possess the necessary education and experience and wish to integrate singing bowls into your medical practice, it's entirely reasonable. You would require professional Healingbowl® singing bowls and need to learn both contact and distant Healingbowl® techniques. Incorporating singing bowls as a supplementary treatment can notably shorten the recovery period.
</p>
       <p>When used correctly, professional singing bowls can normalize metabolic processes, improve cellular microcirculation, ease muscle tension, decrease psycho-emotional stress, enhance bodily fluid properties, and provide various other benefits to boost the body's overall recovery. It's vital to understand and familiarize yourself with necessary precautions and contraindications. Learn the Healingbowl® techniques either in-person or remotely. Take note of the unique 'Vibropuncture' method, developed by S.V. Surikov, the owner of the Healingbowl® brand.
</p>",
];